version: '3'
service:
    web:
      image: docker-chat-app-server
      build: ./
      command: node app.js
      ports:
        - "3000:3000"
      volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
      depends on:
        - "mongo"

    mongo:
        image: "mongo"
        ports:
          - "27017:27017"